<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MAGHRABI-Remote-Agent</AssemblyName>
    <RootNamespace>MaghrabiRemoteAgent</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>MAGHRABI</Authors>
    <Description>Personal MAGHRABI Remote Agent for secure device heartbeat.</Description>
  </PropertyGroup>
</Project>
